### PR TITLE
Fixed the padding for #faq-accordian

### PR DESCRIPTION
**Pull request by buoyantair**
I've fixed the padding for the #faq-accordian element as requested in #579

### CODE REVIEW

**Comment by arun1595** [comment]
@buoyantair Thanks for submitting the PR :smile: 

Instead of adding a style definition to `static_pages.scss`, all you have to do is remove [this](https://github.com/TheOdinProject/theodinproject/blob/redesign/app/assets/stylesheets/components/faq.scss#L6) line

**Comment by arun1595** [comment]
@buoyantair Looks like you checked out `fix/Redesign-Remove-the-padding-from-FAQ-accordion` from `master`.

You should instead check out the new branch from `redesign`

**Comment by buoyantair** [comment]
@arun1595 Ahhh I didn't see that coming, I'll try to do it.

**Comment by buoyantair** [comment]
Ops, closed this by mistake >.<

**Comment by buoyantair** [comment]
@arun1595 Okay, fixed this again.

**Comment by arun1595** [comment]
@buoyantair 

>  Okay, fixed this again.

No, it is not fixed yet. The commits appearing above are from `master` branch. Can you please open a new PR with changes based-off `redesign` branch?

Let us know in the contributing channel if you've any questions. Thanks!

**Pull request closed without merging**
