### PR TITLE
Added social option on navbar

### PR DESCRIPTION
**Pull request by KevinMulhern**
The current method of finding groups on odin is cumbersome as the user has to go into the account dropdown and then into study groups and then scan through the list of meet ups. It's hidden in a sense and I would bet money that some users on TOP haven't even found the list of meetups and groups because you really have to go looking for it.

A social drop down right on the navbar will be immediately visible and will be much more user friendly. with the integration of a slack chat it will make the odin project a much more social experience by bringing together everyone who is working through it.

### CODE REVIEW

**Comment by eriktrautman** [comment]
Hi Kevin, where did the Heroku app come from and how does it link to Slack?  We have an existing Slack group that we're working on linking with the rest of the course.

**Comment by KevinMulhern** [comment]
Hi Erik,
I used this project to set up the invite page: https://github.com/rauchg/slackin. I can add you to and whoever else you want as admins to the slack we setup if you wish. We all ready have quite a few users who have signed up.

**Comment by KevinMulhern** [comment]
sorry, I forgot to mention It links to slack using an api key.

**Comment by nhquiroz** [comment]
I think this feature is a must. Facebook group is quite hidden (only 197 members by now, I think the number of TOP registered users can be ten times that or more, statistics are needed too.). Also the channel is a must to provide instant feedback and help by the community and for the community. 

I've checked the Pivotal Tracker too and it's true there isn't any mention about something related, so I think it's better to use the existing one (which already has some users) instead of creating another.

**Comment by KevinMulhern** [comment]
Hey Erik, any word on this? sorry for my lack of patience. Just really anxious to get things moving.

**Comment by eriktrautman** [comment]
Whatever Slack integration we do, I'd like to link with our existing Slack channel (https://theodinproject.slack.com).  The Slackin tool is useful for this certainly.  @hgducharme and @craftykate have been running point on this but it's tricky sometimes for them to find the bandwidth to take on a PR like this since it requires integrating with their existing solutions.  When we roll out chat, we're going to do so completely (including email integration) and not piece-by-piece, so it's part of a larger strategy here and can't be implemented one bit at a time, hence the delay.  With 20,000 members on the site here, it needs to be done with some care.

**Comment by KevinMulhern** [comment]
I totally understand if you want to use the existing slack, It could be easily integrated with what I have already done. It only takes 20 minutes to set up a new slackin page. Im obviously not privy to the vision that you have for chat on TOP, but I think that waiting until you have everything done with email integration etc, before you integrate a chat feature is the wrong way to go about things, especially when a good solution already exists and can be integrated in a short period of time. I have spoken to many TOP students about a chat feature and the demand is definitely there. Regardless,  I would be more than willing to help out if you need more man power with the feature's you have in mind. 

My main inspiration for this PR was freecodecamps chat, it is the main feature that makes FCC standout and more makes it attractive to students. They use a pretty much identical solution with slack and email invites and it seems to be working out pretty well for them.

**Comment by nhquiroz** [comment]
What's the point of integrating mail with slack? How long will this "larger strategy" take?
People are migrating to FreeCodeCamp for "details" like this, just saying. If you don't believe me, google some reviews, read the opinions.

**Comment by eriktrautman** [comment]
Have pulled this in and updated the welcome email to include a link to it.  Updated the links to point to the existing Slack channel and Slackin.  Thanks a lot for putting this together.  Will send an email to the students and call for moderators when able.  It'll be good to get a slow trickle of people into the chat at first just to test the dynamic anyway.

**Comment by jlampe1985** [comment]
Are you using the slack you have created?  https://theodinproject.slack.com

**Comment by eriktrautman** [comment]
Yes

**Pull request merged**
