### PR TITLE
Moved guides into docs

### PR DESCRIPTION
**Pull request by KevinMulhern**
This puts the guides under odin ownership instead of as gists of two different people. I also added a step to prepare the test database to both guides which was overlooked before.

Ticket for this PR:
https://trello.com/c/amDQiPhN/22-move-main-site-set-up-guides-over-to-be-odin-as-readme-s

### CODE REVIEW

**Comment by KevinMulhern** [comment]
@eriktrautman I added these to the docs because it seemed like the best place to put them. But if there is a better folder please let me know.

**Comment by eriktrautman** [comment]
I don't think there is a better place for it at the moment so this should work well

**Comment by KevinMulhern** [comment]
Great stuff, ready to merge :+1:

**Comment by KevinMulhern** [comment]
@eriktrautman could I get this merged please :)

**Pull request merged**
