### PR TITLE
Chore: Remove admin column from users

### LINKED ISSUE #4712: Remove admin column from users
### Because:
- It is no longer needed

### Acceptance criteria:
- Drop the admin column from users
- It will also need to be removed from the users factory

### Notes:
- It'll need to be dropped using a data migration - basic Rails knowledge is needed.

### PR DESCRIPTION
**Pull request by davidumoru**
## Because
The admin column in the users database is no longer needed

## This PR
- Drop the admin column from users
- Remove admin from the users factory

## Issue
Closes #4712

## Additional Information
nil

## Pull Request Requirements
-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [x] The title of this PR follows the `keyword: brief description of change` format, using one of the following keywords:
    - `Feature` - adds new or amends existing user-facing behavior
    - `Chore` - changes that have no user-facing value, refactors, dependency bumps, etc
    - `Fix` - bug fixes
-   [x] The `Because` section summarizes the reason for this PR
-   [x] The `This PR` section has a bullet point list describing the changes in this PR
-   [x] I have verified all tests and linters pass after making these changes.
-   [x] If this PR addresses an open issue, it is linked in the `Issue` section
-   [ ] If applicable, this PR includes new or updated automated tests

### CODE REVIEW

**Review by KevinMulhern — CHANGES_REQUESTED** [review]
Thanks @davidumoru, but the schema file doesn't look quite right. There are  changes to database views that don't appear to belong in this PR and the migration number hasn't been updated. 

Can you reset your schema file to main and try running db:migrate again please?

**Review by KevinMulhern — CHANGES_REQUESTED** [review]
This is _almost_ there @davidumoru, the [schema version](https://github.com/TheOdinProject/theodinproject/blob/8c700cbda869f8d3c4deb4f572eb63a9126e40ab/db/schema.rb#L13) should have automatically updated to match your migration timestamp after it was run. Thats why the tests are failing. Please make sure thats committed! 

Running db:migrate again should set it.

Otherwise, you can roll back and then run the migration again 
`rails db:rollback`
 `rails db:migrate`

**Comment by davidumoru** [comment]
Hey @KevinMulhern, I've run the migration again

**Review by KevinMulhern — APPROVED** [review]
Great stuff, thank you @davidumoru!

**Pull request merged**
