### PR TITLE
Overhaul contributing page

### PR DESCRIPTION
**Pull request by muzfuz**
Changes as per Trello card:

https://trello.com/c/7jjbGbFj/18-simplify-the-contributing-page-on-the-main-site

### CODE REVIEW

**Comment by muzfuz** [comment]
@eriktrautman @KevinMulhern ^^

**Comment by KevinMulhern** [comment]
I don't think there is a better place to point them @muzfuz, we can make adjustments to the read me on the curriculum repo to provide more details about the different curriculum based contributions that can be made.

**Comment by muzfuz** [comment]
@KevinMulhern made a few more adjustments.  Mainly formatting, but I also removed the 'contact us' section, since presumably the Slack channel takes care of that - and the Google group seems a bit defunct :)

**Comment by KevinMulhern** [comment]
Good call @muzfuz, yeah slack should be the main hub of communication with contributions and the google group hasn't been used in ages. Let me know when you are satisfied with it and consider it to ready to merge please :)

**Comment by muzfuz** [comment]
Cool I'm happy to merge ;)

**Comment by eriktrautman** [comment]
This is a great clarification.  It feels good to breathe deep and not see a wall of text.  Thank you for this!

**Pull request merged**
