### PR TITLE
Feature: Admin v2 - Team activity log

### PR DESCRIPTION
**Pull request by KevinMulhern**
Because:
- When something unexpected happens with a team member, I want to view an activity log, so I can find out what happened.

This commit:
- Adds the public activity gem
- Adds a dropdown to the team page header to access the activity log
- Creates a new activity when an invite is created
- Creates a new activity when a team member is deactivated
  - Removes the deactivated_by column from admin users since activities provides a better way of tracking this.

https://github.com/user-attachments/assets/be7350e1-6256-4bd0-8428-59ac3a3e3aa1

### CODE REVIEW

**Comment by KevinMulhern** [comment]
Note: this can only be tested locally, we can't send emails on review apps.

### Steps for QA

1. Visit /admin_v2 and sign in with - [admin@odin.com](mailto:admin@odin.com), password123
2. Invite a new team member
3. Within the invitation email, open the "Accept invitation" link in a new incognito window
4. Fill in the new password and submit
5. Back on the admin@odin.com account, deactivate the newly invited admin from the dropdown on their team member item
6. Open the activity log from the ellipsis icon beside the invite team member button
7. The activity log should include the your invite and deactivation activities

**Comment by Asartea** [comment]
Was trying to play with this locally, but getting errors:
image

```
 Showing /home/asartea/theodinproject/repos/theodinproject/app/views/admin_v2/team/activities/index.html.erb where line #12 raised:

undefined method `with_indifferent_access' for an instance of String
```

**Comment by KevinMulhern** [comment]
Try running bundle install to see if that makes any difference @Asartea. I think that might be coming from the public activity gem.

**Comment by Asartea** [comment]
Tried that, but didn't help, and `public_activity` is installed:
```bash
gem list -i "^public_activity$"
> true
gem list | grep 'public_activity'
public_activity (3.0.1)
```

**Comment by KevinMulhern** [comment]
Can you see what `@activites` contains in the console at the bottom of the error page?

**Comment by Asartea** [comment]
```ruby
>> 

p @activities

=> #<ActiveRecord::Relation [#<PublicActivity::Activity id: 2, trackable_type: "AdminUser", trackable_id: 9, owner_type: "AdminUser", owner_id: 1, key: "admin_user.deactivated", parameters: "{}", recipient_type: nil, recipient_id: nil, created_at: "2024-07-23 13:16:41.525192000 +0000", updated_at: "2024-07-23 13:16:41.525192000 +0000">, #<PublicActivity::Activity id: 1, trackable_type: "AdminUser", trackable_id: 9, owner_type: "AdminUser", owner_id: 1, key: "admin_user.invited", parameters: "{}", recipient_type: nil, recipient_id: nil, created_at: "2024-07-23 13:16:04.456848000 +0000", updated_at: "2024-07-23 13:16:04.456848000 +0000">]>
```

**Comment by KevinMulhern** [comment]
I found an issue on the PublicActivity repo, that does seem to be an issue that sometimes happens. I've pushed up something that should hopefully fix it. You'll be best off deleting your local branch and refetching. I've fixed a few conflicts and rebased too.

I'd reset the database while on main branch too - `bin/rails db:reset`

**Comment by Asartea** [comment]
QA:
1. Visit /admin_v2 and sign in with - [admin@odin.com](mailto:admin@odin.com), password123 ✅ 
2. Invite a new team member ✅ 
3. Within the invitation email, open the "Accept invitation" link in a new incognito window ✅ 
4. Fill in the new password and submit ✅ 
5. Back on the [admin@odin.com](mailto:admin@odin.com) account, deactivate the newly invited admin from the dropdown on their team member item ✅ 
6. Open the activity log from the ellipsis icon beside the invite team member button ✅ 
7. The activity log should include the your invite and deactivation activities
image

**Comment by KevinMulhern** [comment]
Thanks @Asartea 💪 

> Is it intentional that only invites and deactivations show up for now? I'm not seeing reactivations, accepting an invite, and 2FA resets

Yep, thats intentional. I wanted to keep this PR small and two activities makes sure the structure/patterns are generic enough. The rest of the activities have stories here: https://github.com/orgs/TheOdinProject/projects/46/views/1

**Pull request merged**
