### PR TITLE
Fix/headings hierachy

### LINKED ISSUE #3965: Fix some headings not following the proper hierachy
Complete the following REQUIRED checkboxes:

-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [x] The title of this issue follows the `brief description of request` format, e.g. `Add dark mode to website`

The following checkbox is OPTIONAL:

-   [x] I would like to be assigned this issue to work on it

<hr>

**1. Description of the Feature Request:**
Some headings aren't following proper hierarchy behavior (ie, they aren't properly arranged in sequential descending order). As a spot check I noticed this on the following pages:

- `/about`, the text "Help the Odin Project stay current and meaningful to all future students, please contribute!" is a `h4`. I think the next higher up is a `h2`, but as the container its in is a direct descendant of the `body` element I think it would make more sense to convert it to a simple `div`
- `/faq`, all the faq headings are `h3` while the "Frequently Asked Questions" itself is `h1`. All of the `h3`'s should be converted to `h2`
- `/paths`, the "start here" and "PATH" headings are `h3`'s. Again I don't think these necessarily make sense as headings; should just be converted to a `div` or a `p`

**2. Acceptance Criteria:**
- [ ] `/about` is fixed
- [ ] `/faq` is fixed
- [ ] `/paths` is fixed

**3. Additional Information:**
Could be a decent first issue?

### PR DESCRIPTION
**Pull request by luuu-xu**
## Because

Some headings of our static pages are not using the correct hierarchy.

## This PR

1. For `/faq` page, changed `components/faq/item_component.html.erb` heading from `h3` to `h2`.
2. For `/about` page, changed `views/shared/_bottom_cta.html.erb` heading from `h4` to `h2`.
3. For `/contributing` page, changed two headings's hierarchy.

## Issue

Closes #3965 

## Pull Request Requirements

-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [x] The title of this PR follows the `keyword: brief description of change` format, using one of the following keywords:
  - `Feature` - adds new or amends existing user-facing behavior
  - `Chore` - changes that have no user-facing value, refactors, dependency bumps, etc
  - `Fix` - bug fixes
-   [x] The `Because` section summarizes the reason for this PR
-   [x] The `This PR` section has a bullet point list describing the changes in this PR
-   [x] I have verified all tests and linters pass after making these changes.
-   [x] If this PR addresses an open issue, it is linked in the `Issue` section
-   [ ] If applicable, this PR includes new or updated automated tests

### CODE REVIEW

**Comment by Asartea** [comment]
🚀

**Review by CouchofTomato — APPROVED** [review]

**Comment by CouchofTomato** [comment]
Can we resolve the merge conflicts please.

**Comment by luuu-xu** [comment]
Per @KevinMulhern @Asartea, the `_bottom_cta.html.erb` should have its heading as a `h2` instead of a `h4`. The conflict is solved.

**Comment by CouchofTomato** [comment]
image

Sorry for being unclear. There are merge conflicts as your branch has diverged from our branch. Are you familiar with how to solve this?

**Comment by luuu-xu** [comment]
> There are merge conflicts as your branch has diverged from our branch. Are you familiar with how to solve this?

@CouchofTomato By looking at my Git Graph I see what is wrong now! Somehow when I first contributed in June, I have been merging TOP's main branch into my main branch so my origin/main branch is like always 5 commits ahead and also some commits behind of TOP/main branch... 

What is the best way to approach it though? Maybe I should just refork and clone TOP and remake the the PR? Sorry for my mistakes, it must have been one or two wrong git commands that messed up my origin/main branch.

**Comment by CouchofTomato** [comment]
When you merge in main you should see the merge conflicts and can fix them and then commit and push up.

If it all seems a bit confusing though then plesae feel free to open a new PR and we can close this once that has been merged.

**Pull request closed without merging**
