### PR TITLE
Feature: add link to go back to a lesson from project submissions page

### LINKED ISSUE #3518: Add link to go back to project on Solutions page
Complete the following REQUIRED checkboxes:

-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [x] The title of this issue follows the `brief description of request` format, e.g. `Add dark mode to website`

The following checkbox is OPTIONAL:

-   [ ] I would like to be assigned this issue to work on it

<hr>

**1. Description of the Feature Request:**

If you open up a project page and click "View full list of solutions" at the bottom, that [Solutions page](https://www.theodinproject.com/lessons/534/project_submissions?page=5) doesn't have a link to go back to the project page.

**2. Acceptance Criteria:**

- [ ] On the Solutions page, the project title should be a link to that project

**3. Additional Information:**

### PR DESCRIPTION
**Pull request by scheals**
## Because
There's no easy way to navigate back to the lesson one is currently on when browsing its submissions page.

## This PR
- Adds a link to go back to lesson while browsing project submissions.

image

## Issue

Closes #3518 

## Additional Information

The way this is implemented it probably will get user to land on the very top of the page as if they were there first time. Possibly for best UX, we should get them back to the `Solutions` component but that'd require having an anchor in there. Not sure if that anchor would render in the `Lesson contents` and if that'd be something we want to happen. We possibly might make the link anchor onto `Additional Resources` - somewhat close and we have that already.

## Pull Request Requirements

-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [x] The title of this PR follows the `keyword: brief description of change` format, using one of the following keywords:
  - `Feature` - adds new or amends existing user-facing behavior
  - `Chore` - changes that have no user-facing value, refactors, dependency bumps, etc
  - `Fix` - bug fixes
-   [x] The `Because` section summarizes the reason for this PR
-   [x] The `This PR` section has a bullet point list describing the changes in this PR
-   [x] I have verified all tests and linters pass after making these changes.
-   [x] If this PR addresses an open issue, it is linked in the `Issue` section
-   [ ] If applicable, this PR includes new or updated automated tests

### CODE REVIEW

**Review by ChargrilledChook — COMMENTED** [review]
At a glance LGTM :+1: simple and effective.

The tests are having problems running in CI for some reason, I'm guessing because your pull is coming from a fork, but odd that it's not also breaking seeds and linters :thinking:

**Comment by KevinMulhern** [comment]
Sorry for the trouble @scheals, this branch will need rebased to bring in the fix for CI.

Assuming your remote to upstream is named upstream, on your local branch, running `git pull --rebase upstream main` and then force pushing (`git push -f`) should do the trick.

**Comment by scheals** [comment]
@KevinMulhern No problem at all, it ain't much work to do so. Should be done now, going to do the same for the other PR as requested.

**Review by KevinMulhern — CHANGES_REQUESTED** [review]
Thanks for putting this together @scheals, agreed on taking users back to the solutions part of the lesson page being better UX. We'll have to pass the lesson url into the submissions react component and turn the submission title into a link. We could do that in a follow up if you want?

From a design point of view, I think top left would be a more effective position than bottom centre. Users will intuitively look at that part of the page for the way back due to the browser back button being located on that part of the screen.

I've been playing around a little with the design and think we do a little to blend it in with the rest of the content. This is where I landed:
Screenshot 2023-01-14 at 17 05 10

Heres the markup for it:
```erb
 <div>
    <%= link_to @lesson, class: "inline-flex items-center pb-10 text-gray-600 text-base hover:text-gray-800 dark:text-gray-400 dark:hover:text-gray-200 gap-2" do %>
      <%= inline_svg_tag 'icons/arrow-left-circle.svg', class: '', aria: true, title: 'Back to lesson icon' %>
      Back to lesson
    <% end %>
  </div>
```

For the icon, you'll have to grab the `arrow-left-circle` icon from [Heroicons](https://heroicons.com/)
 and put it in the `app/assets/images/icons` folder

**Comment by scheals** [comment]
@KevinMulhern Cheers for help, I think everything is in the right place :D Thanks to this I have an idea how to possibly something else but that'll require an issue of its own :D 

I will also create an issue to include running `erblint --lint-all` when doing PRs and try to track down instructions that go over what kind of tests have to be ran after doing a change, so I can then submit a PR.

**Comment by ChargrilledChook** [comment]
> @KevinMulhern Cheers for help, I think everything is in the right place :D Thanks to this I have an idea how to possibly something else but that'll require an issue of its own :D 
> 
> I will also create an issue to include running `erblint --lint-all` when doing PRs and try to track down instructions that go over what kind of tests have to be ran after doing a change, so I can then submit a PR.
> 
> 

@scheals Running `bin/test` will run all linters and specs, including JS and ERB. I thought I had documented this I'm the relevant spot but it's very possible it needs to be highlighted more. I have a PR to update the README too

**Review by KevinMulhern — APPROVED** [review]
This is a great quality of life improvement, thanks for this @scheals 🚀

**Pull request merged**
