### PR TITLE
Getting involved page

### PR DESCRIPTION
**Pull request by Alehanz**
Added a "Getting involved page" (linked from the Contributing page) and tests for it.

### CODE REVIEW

**Comment by eriktrautman** [comment]
Hey Alexey just following up, looks like you've got a number of merge conflict markers present in the file (the <<<< HEAD-type things).  If you clean those up we can review the page itself

**Comment by Alehanz** [comment]
Thank you for pointing that out! I think this time I got them all.

**Comment by eriktrautman** [comment]
The code seems good, I'll try to give it a better look this weekend

**Comment by Alehanz** [comment]
Great! Glad to hear that.

**Comment by eriktrautman** [comment]
Merged it in.  Was on the fence about a full-html page vs just loading in the markdown like with the legal pages but looks fine.  Thanks!

**Comment by Alehanz** [comment]
Awesome, thank you!

**Pull request merged**
