### PR TITLE
Chore: update ruby lesson urls & rename course to "Ruby"

### PR DESCRIPTION
**Pull request by 01zulfi**
Complete the following REQUIRED checkboxes:

-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [x] The title of this PR follows the `keyword: brief description of change` format, using one of the following keywords:
  - `Feature` - adds new or amends existing user-facing behaviour
  - `Chore` - changes that have no user-facing value, refactors, dependency bumps, etc
  - `Fix` - bug fixes

Complete the following checkbox ONLY IF it is applicable to your PR. You can complete it later if it is not currently applicable:
-   [x] I have verified all tests and linters pass against my changes, and/or I have included automated tests where applicable

<hr>

**1. Because:**

Related to: 
1. https://github.com/TheOdinProject/top-meta/issues/109
2. https://github.com/TheOdinProject/curriculum/pull/23846

**2. This PR:**

1. Updates ruby lesson urls based on https://github.com/TheOdinProject/curriculum/pull/23846
2. Renames Ruby Programming course title to Ruby

**3. Additional Information:**

n/a

### CODE REVIEW

**Comment by KevinMulhern** [comment]
Hey @01zulfi, thanks so much for doing this 💪 

There are a couple more small spots we need to update for this as well.

The badges for each course are fetched using the title:
https://github.com/TheOdinProject/theodinproject/blob/main/app/components/progress_badge_component.rb#L29
https://github.com/TheOdinProject/theodinproject/blob/main/app/components/progress_badge_component.rb#L43

Finally, there is a mention of Ruby programming in the readme:
https://github.com/TheOdinProject/theodinproject/blame/main/README.md#L7

**Comment by 01zulfi** [comment]
Above changes done

**Comment by KevinMulhern** [comment]
Changes look good thanks @01zulfi, lets get the curriculum changes merged, then I'll do a quick QA in a review app before merging this PR.

**Comment by 01zulfi** [comment]
@KevinMulhern Curriculum changes merged.

**Review by KevinMulhern — APPROVED** [review]
LGTM @01zulfi, thanks for all your work on this. Merging now to fix the improve this lesson links on the ruby course.

**Pull request merged**
