### PR TITLE
Add line numbers to code blocks

### LINKED ISSUE #1054: Enable Line Numbers for Code Snippets
In the TOP lessons, code snippets are frequently referred to by line number. This is currently inconvenient, because line numbers are not shown. 

As far as I know we use kramdown for markdown conversion. And I found a potential solution to enable line numbers here: https://github.com/jekyll/jekyll/issues/4619 
```
kramdown:
    syntax_highlighter_opts:
        block:
            line_numbers: true
```

I have a setup of TOP locally, but I don't know where to insert that code.

### PR DESCRIPTION
**Pull request by arku**
### Description

Adds [Line numbers](https://prismjs.com/plugins/line-numbers/) plugin to Prism.

Fixes #1054 

### Screenshots

image

image

### CODE REVIEW

**Comment by nearmint** [comment]
This works great! Thank you @arku. 
One example, where code snippets are referred to by line numbers is here: https://www.theodinproject.com/courses/javascript/lessons/factory-functions-and-the-module-pattern

I think this is a good improvement.
Thanks again @arku

**Comment by arku** [comment]
@nearmint Thanks for the review!

I just updated the PR description with a screenshot from `/courses/javascript/lessons/factory-functions-and-the-module-pattern`.

**Comment by mindovermiles262** [comment]
Merging and pushing to staging

**Comment by nearmint** [comment]
I notice two issues, first issue:
Selection_051
Taken from: https://staging-odin-project.herokuapp.com/courses/javascript/lessons/objects-and-object-constructors
As you can see, there is a line under line number 3 which is not numbered. That is probably because the code snippet doesn't have a high enough width to display the full line. I'm not sure if we need to fix these cases somehow (higher width, or a line break) or whether we want to leave this as-is.

2. In general I noticed that the line numbers are not in the center of the line, but rather start somewhat "under" the line. 
OnPaste 20200118-220648
I need your opinion whether that's acceptable.

**Comment by dvik1950** [comment]
I think #1 isn't really an issue. One way to make it look better would probably be splitting long comments into multiple rows but it's kinda fine now as it is imo.

**Pull request merged**
