### PR TITLE
Update 05_html_css_course_seeds.rb

### PR DESCRIPTION
**Pull request by 105ron**
For Grid and Flex lesson

### CODE REVIEW

**Comment by CouchofTomato** [comment]
Thanks @105ron 

Sorry I've been meaning to look at this. Are we not creating a separate section for positioning or do you want to do that later and just get these live for now?

**Comment by 105ron** [comment]
I didn't realise we were going to make a separate section for positioning. We can do that if you like?

**Comment by 105ron** [comment]
This is the current order of the section:

1. CSS Basics
2. The Box Model
3. Floats and Positioning
4. Flexbox
5. Grid
6. Project: Positioning and Floating Elements
7. Best Practices
8. Backgrounds and Gradients
9. Project: Building with Backgrounds and Gradients

What did you want swapped around @mindovermiles262 ? I think Flexbox should come before grid since grid is somewhat a 2 axis flexbox.

**Comment by mindovermiles262** [comment]
Heh not sure what I was seeing a few days go

LGTM +1

**Comment by KevinMulhern** [comment]
👍LGTM

**Pull request merged**
