### PR TITLE
Fix: set lesson h3 headings width to fit-content

### PR DESCRIPTION
**Pull request by 01zulfi**
Complete the following REQUIRED checkboxes:

-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [x] The title of this PR follows the `keyword: brief description of change` format, using one of the following keywords:
  - `Feature` - adds new or amends existing user-facing behaviour
  - `Chore` - changes that have no user-facing value, refactors, dependency bumps, etc
  - `Fix` - bug fixes

Complete the following checkbox ONLY IF it is applicable to your PR. You can complete it later if it is not currently applicable:
-   [x] I have verified all tests and linters pass against my changes, and/or I have included automated tests where applicable

<hr>

**1. Because:**

1. Related to: 
   1. https://github.com/TheOdinProject/curriculum/pull/23835
1. Lesson headings (`h3`) can not be easily selected via a cursor.

**2. This PR:**

1. Sets lesson headings to `fit-content` to alleviate that.

**3. Additional Information:**

n/a

### CODE REVIEW

**Comment by bappyasif** [comment]
and here i thought it was all markdown!! 😁

**Review by KevinMulhern — APPROVED** [review]
Brilliant solution @01zulfi, it works great 👏 

Is there somewhere I could read up on how this works? I searched a little but couldn't find much.

**Comment by 01zulfi** [comment]
@KevinMulhern  I'm afraid I don't exactly I understand what you mean by "... how this works?".

I can give you a summary about this pull request. 

Basically, `h3`'s a block-level element, thus its width stretches to fill the container:

image

We know `h3` heading's text are links; this comes with a hover effect. This hover effect is present throughout the entire width of the heading (shown in lightblue in the above screenshot). Specifically, the hover effect throughout the width makes it a little harder to select the heading text via a cursor. This is what I mean by selecting the text:

image

Wait a minute, `a`'s are inline elements, so why does it stretch to fill the width of its parent element? I'm convinced it's mostly because of `display: flex` we define on it in [internal_link.scss](
https://github.com/TheOdinProject/theodinproject/blob/main/app/assets/stylesheets/components/internal_link.scss#L4)

Fix was simple, really. I could've either put `width: fit-content` on the lesson heading or in the `internal-link` class. Both achieve the desired result: 

image

This allows us to select the text from both sides of the text.

I'm still not sure if this was the answer you're looking for, do let me know.

**Comment by KevinMulhern** [comment]
Sorry for not being clear, yeah I meant how width: fit-content specifically fixed it. Thanks for the detailed answer 👏

**Comment by bappyasif** [comment]
bravo @01zulfi, nicely explained, much appreciated, thanks :)

**Pull request merged**
