### PR TITLE
Chore/upgrade to ruby 3.1

### LINKED ISSUE #2860: Chore: Upgrade to Latest Version of Ruby
**1. Acceptance Criteria:**
The App is running on the latest version of Ruby - 3.1.2

**3. Additional Information:**

Our CI ruby image will also need to be updated: https://github.com/TheOdinProject/theodinproject/blob/main/.circleci/config.yml#L7

### PR DESCRIPTION
**Pull request by ChargrilledChook**
-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [x] The title of this PR follows the `keyword: brief description of change` format
-   [x] I have verified all tests and linters pass against my changes, and/or I have included automated tests where applicable

<hr>

**1. Because:**

Closes #2860

**2. This PR:**

* Bump Ruby version
* Manually add ActionMailer dependencies that were removed from the core library (temp workaround)
* Bump bundler version to fix deprecation warnings
* Change Circleci config to use new image type
* Run Rubocop autofix on two new offences introduced by 3.1 changes

**3. Additional Information:**

Although there are lots of file changes, most are Rubocop fixes (either using new default hash value syntax or anonymous block forwarding).

Main files that need review are the circleci config and the Gemfiles

### CODE REVIEW

**Review by KevinMulhern — APPROVED** [review]
Looks great to me @ChargrilledChook 🏅  

Before I merge, can you squash the commits please? thanks again for doing this mate 🥳

**Comment by ChargrilledChook** [comment]
@KevinMulhern Sure thing, squash away (should I do that myself next time?)

Happy to help out, the Odin app is a pleasure to work with. Being able to jump a major and a minor version so easily is the dream, I wish it was always this smooth 😅

**Comment by KevinMulhern** [comment]
I can't squash any commits on this branch because originates from a fork unfortunately @ChargrilledChook. Would you mind doing it mate? we have some [docs](https://github.com/TheOdinProject/theodinproject/wiki/Squashing-Commits) if needed. 

We usually push up as many commits as needed before and during review exactly as you've done here. Then squash after getting approved/ before merging for that clean ™️  git history.

**Comment by ChargrilledChook** [comment]
@KevinMulhern Sorted, how's this look? [Commit](https://github.com/TheOdinProject/theodinproject/pull/2882/commits/52a0185c5413c56fbffe79c2047c55a172758416)

**Comment by KevinMulhern** [comment]
Looks perfect 👌 thanks @ChargrilledChook 💪

**Pull request merged**
