### PR TITLE
redirect /courses to /tracks

### PR DESCRIPTION
**Pull request by mindovermiles262**
Solves #1015 where /courses should point to /tracks

### CODE REVIEW

**Comment by arku** [comment]
@mindovermiles262 Isn't #1015 solved by https://github.com/TheOdinProject/theodinproject/pull/1028? 🤔

**Comment by mindovermiles262** [comment]
I guess that depends on if we want to be able to access the legacy `/courses` uri

#1028 only changes the button link, whereas this PR will change it for any other buttons that may be hidden inside the application

**Comment by arku** [comment]
@mindovermiles262 Right. But do we always want to redirect to `/tracks`?

**Comment by mindovermiles262** [comment]
I'd say yes. 

`/courses` currently points to only Full Stack RoR but we want to show off the offerings we've worked so hard on.

**Comment by arku** [comment]
> /courses currently points to only Full Stack RoR 

@mindovermiles262 I think we're displaying a list of all the courses there. But I think you're right. It makes sense to display the tracks instead of the all courses page.

**Comment by arku** [comment]
@mindovermiles262 Let's see what others think about this change.

**Comment by mindovermiles262** [comment]
ACK. Let's wait to hear from at least one other RE: if we should redirect `/courses` (displays Full Stack RoR course) to `/tracks` (Displays all available tracks)

**Comment by arku** [comment]
> ACK

🤓

**Comment by mindovermiles262** [comment]
Sounds good. Merging

**Pull request merged**
