### PR TITLE
Setup docker for development

### PR DESCRIPTION
**Pull request by arku**
This is very much a WIP PR. I'll be adding documentation on how to use docker for local development when I get a chance (hopefully in the next few days.)

### CODE REVIEW

**Comment by KevinMulhern** [comment]
Nice work @arun1595!

Is this ready to merge?

**Comment by arun1595** [comment]
@KevinMulhern Not yet. I'll have to add documentation on how to use docker for local development. Will try to do it this weekend.

**Comment by KevinMulhern** [comment]
No problem, feel free to merge it when you think you're finished with it. Thanks again, this is awesome.

**Comment by KevinMulhern** [comment]
@arun1595 yeah that makes sense.

**Comment by mindovermiles262** [comment]
@arun1595 any updates on this?

**Comment by KevinMulhern** [comment]
@mindovermiles262 someone needs to give it a whirl with setting it up on their local machine to see if theres anything missing from the instructions.

**Comment by mindovermiles262** [comment]
@arun1595 Do you have any install instructions?  `docker build .` built okay but appears to have no networking nor DB connections.

**Comment by KevinMulhern** [comment]
Hey @mindovermiles262, instructions are [here](https://gist.github.com/arun1595/12efa1a16d735d144cb47b77b95bf151)

**Comment by mindovermiles262** [comment]
I'm encountering an issue with Node version inside the container -

screenshot_2018-10-01 action controller exception caught

Looks like we need to add a node-update to the dockerfile

**Comment by arku** [comment]
@mindovermiles262 Interesting, the script does install node, see [here](https://github.com/TheOdinProject/theodinproject/pull/929/files#diff-3254677a7917c6c01f55212f86c57fbfR2)

Do you have any clue as to why it is not getting installed?

**Comment by arku** [comment]
Closing due to inactivity.

**Pull request closed without merging**
