### PR TITLE
Fix/lesson content center align

### PR DESCRIPTION
**Pull request by DoviMaj**
@KevinMulhern please let me know if this is acceptable

# Screenshoots
# previous with nav
Screenshot_2020-12-19 How Does the Web Work The Odin Project

# current with nav
Screenshot_2020-12-19 How Does the Web Work The Odin Project(1)

# previous without nav
Screenshot_2020-12-19 Setting Up Git The Odin Project

# current without nav
Screenshot_2020-12-19 Setting Up Git The Odin Project(1)

### CODE REVIEW

**Comment by KevinMulhern** [comment]
Hey @DoviMaj, sorry this one has been sitting around for a while. I was having a look through the bootstrap docs and noticed they have a `container-fluid`. I wonder if using that would be the more standard™️ way of solving this issue.

I'm a little bit nervous about using negative margins, it feels a bit too brittle.    

https://getbootstrap.com/docs/4.0/layout/overview/

**Comment by DoviMaj** [comment]
hey @KevinMulhern. no prob. i see, i tried it with ` container-fluid ` and it solves the width problem but its not responsive, on all viewports it will take 100%. this gif is with `container-fluid`

Peek 2020-12-29 01-36

also the nav will be pretty much on the end of the viewport which dosent look so nice and still taking up a lot of white space on the right.

chrome-capture (4)

but maybe u meant something else?

**Comment by KevinMulhern** [comment]
Yeah I think you will have to experiment with the col sizes for the larger widths. Bootstrap has different classes for different break points you can try playing with https://getbootstrap.com/docs/4.0/layout/grid/#grid-options

**Comment by DoviMaj** [comment]
current behavior
current
</br>
with different col sizes and making the nav container `display: flex` and `justify-content: center` the best i can get is this the screenshot bellow, but notice that the lesson content isnt 100% aligned to the center and on screens larger then  1700px the lesson content gets huge because of `container-fluid`
Peek 2020-12-29 21-02

**Comment by KevinMulhern** [comment]
I think its not centering because the the lesson content col is too large, There are 12 possible columns and the side nav is 3 so to center the lesson content its col needs to be a 6 to leave 3 on the other side. 

try changing the lesson content col to .col-xl-6 and .col-lg-6, it might not even need the xl col class.

**Comment by DoviMaj** [comment]
i tried with `col-lg-6` and it does center the content but still its huge on large screens because its 6 col of 100% width..
and on smaller screens its too small imo.

Peek 2020-12-30 18-38

1024px :
chrome-capture (5)
1440px:
chrome-capture (6)
2260px:
chrome-capture (7)

what do u think @KevinMulhern ?

**Comment by KevinMulhern** [comment]
That looks good to me @DoviMaj, maybe we could give the `lesson-content` a max width for larger screens. But otherwise I think this is the way to go 🚀

**Comment by DoviMaj** [comment]
Do u mean `.lesson` ? because changing `lesson-content`'s `max-width` will make it not be centred. 
changing `lesson` is what i had done in the first solution attempt, which is basically overwriting bootstrap's `container-fluid` for larger screens.  
`.lesson {
    max-width: 1710px;
}`
makes `lesson-content` have a `max-width` of `825px` the exact amount it has currently on larger screens.

Also isnt it too small on smaller screens? 
- 1024px 
changed:
`lesson-content` has 482px width
chrome-capture (9)
current:
`lesson-content` has 690px width
chrome-capture (10)

**Comment by KevinMulhern** [comment]
No not the `.lesson` class, it wraps everything. But we only want a max-width on the lesson content for larger screens.

Can you update this PR with your latest changes please? it would be easier for me to have a play with it and get back to you on what else needs done.

**Comment by DoviMaj** [comment]
updated the PR @KevinMulhern

**Comment by KevinMulhern** [comment]
Just had a play with it @DoviMaj, its looking really good.

Just a couple of tweaks and I think this will be good to go.

1. Can you add `max-width: 825px;` and   `margin: 0 auto;` to the `.lesson-content` class please? that will keep the lesson content the same width as it is now on extra large screens.

2. The transition from extra large to large screens could be a bit smoother, `col-xl-6 col-lg-8` on that column seems to work nicely.

**Comment by DoviMaj** [comment]
Sure. that seems good!

My only concern is the nav bar that is extremly to the left on xxl devices.

chrome-capture (13)

if we shouldnt use `.lesson` we can add a `.lesson-container` class and have `max-width` there without needing to add `max-width` to `lesson-content`.
```
.lesson-container {
    max-width: 1710px;
}
``` 
gives 825px to `lesson-content` and has the position of the nav the same as current.
chrome-capture (14)

**Comment by KevinMulhern** [comment]
If that still works with the sticky scroll then lets get this over the line and go with that.

**Comment by DoviMaj** [comment]
dont merge yet..i have to change something still

**Comment by DoviMaj** [comment]
Ok. this is good to go imo. Let me know if its all good.

**Review by KevinMulhern — APPROVED** [review]
Works brilliantly @DoviMaj, thanks for all your work on this.

**Pull request merged**
