### PR TITLE
removed background from badges

### PR DESCRIPTION
**Pull request by srtkverma**
removed the white background from in-progress badges to better support "The Odin Project Dark Theme" plugin
Screenshot from 2019-07-09 14-21-25
Screenshot from 2019-07-09 14-40-23

### CODE REVIEW

**Comment by mindovermiles262** [comment]
Hey @srtkverma 

Does this affect the day mode version of TOP? Can you please provide screenshots of the day version as well?

Thanks

**Comment by srtkverma** [comment]
@mindovermiles262 
Screenshot from 2019-07-15 17-38-36
would like to point out that the PR on this and the extension both have to be merged for it to look good. Would look bad if one of the PRs is merged.

**Comment by KevinMulhern** [comment]
👍 LGTM

**Comment by arku** [comment]
@srtkverma Thanks for your patience!

**Pull request merged**
