### PR TITLE
Feature: Add screencast link to README to giving overview for contributors

### PR DESCRIPTION
**Pull request by JohnathanCh**
## Because

This PR adds an interactive screencast to the README that gives a general overview of the contributing guide to new collaborators. It helps people who may be new to contributing to this or any other repo get a sense of the code base and how to get it running locally. I used a new Scrimba feature that lets one make a video screencast with all the assets of a github repo.

## This PR

- Added link to interactive screencast (scrim) to __README__ in the __Contributing__ section

## Issue

Related to #3470

## Additional Information

Here is a link to the screencast (scrim): https://scrimba.com/scrim/cEggQncE
I can also turn this into an image that links to the scrim video instead of text if you prefer that.

## Pull Request Requirements

-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [x] The title of this PR follows the `keyword: brief description of change` format, using one of the following keywords:
  - `Feature` - adds new or amends existing user-facing behavior
  - `Chore` - changes that have no user-facing value, refactors, dependency bumps, etc
  - `Fix` - bug fixes
-   [x] The `Because` section summarizes the reason for this PR
-   [x] The `This PR` section has a bullet point list describing the changes in this PR
-   [ ] I have verified all tests and linters pass after making these changes.
-   [x] If this PR addresses an open issue, it is linked in the `Issue` section
-   [ ] If applicable, this PR includes new or updated automated tests

### CODE REVIEW

**Comment by ManonLef** [comment]
Wow looks like you've put in quite some work on this! Thanks for that. 

One question/concern I have, which might be due to me not entirely grasping the Scrimba environment yet: What would happen to this scrim if/when we update our documentation?

**Comment by JohnathanCh** [comment]
@ManonLef 

Thanks Manon!

I asked your question about updates being reflected in the scrim and I'm waiting on a response.

**Comment by JohnathanCh** [comment]
@ManonLef 

Our dev answered:
> Each repo recording is linked to a specific commit. So updates to the repository won’t break the recording, e.g: renaming or deleting a file that’s used in the scrim won’t break the scrim.

**Review by KevinMulhern — APPROVED** [review]
Thanks for doing this @JohnathanCh, the walk through of the app in the second half is a really nice touch 🔥 

I share Manon's concern about this potentially becoming out of date when we update our docs. But looking at the [contributing guides history](https://github.com/TheOdinProject/theodinproject/commits/main/CONTRIBUTING.md), it looks like it's been fairly stable for a while outside of minor updates. So we'll cross that bridge when/if we come to it.

Thanks again!

**Comment by jxc876** [comment]
hey @JohnathanCh the scrimba link is now dead, see #4852 

Wondering if you deleted the content by any chance?

**Pull request merged**
