### PR TITLE
Added an image.

### PR DESCRIPTION
**Pull request by malaikaMI**

### CODE REVIEW

**Comment by mindovermiles262** [comment]
Hey @malaikaMI what's the purpose of this PR?

Thanks

**Comment by malaikaMI** [comment]
@mindovermiles262 The purpose is just for provide the user a better interface and a better UI of README.md.

**Comment by malaikaMI** [comment]
And that was a little and pretty addition for me.

**Comment by malaikaMI** [comment]
Andy , The purpose is just for provide the user a better interface and a
better UI of README.md.

**Comment by malaikaMI** [comment]
And that was a little and pretty addition for me.

**Comment by mindovermiles262** [comment]
Hi @malaikaMI 

The README.md is designed to be mostly text so that all browsers and text editors can render the page quickly. As such I don't think this image is appropriate for the page.

We appreciate your want to contribute to The Odin Project and hope that you'll be able to contribute in the future :smile:

**Comment by malaikaMI** [comment]
Hi,Andy you are right.Thanks

**Pull request closed without merging**
