### PR TITLE
Update 404 page

### LINKED ISSUE #988: New 404 Page Image
New image can be found here: https://www.dropbox.com/s/pdsfqwovdpyamhy/404-island.svg?dl=0

### PR DESCRIPTION
**Pull request by arku**
Closes #988 

The change has been deployed to staging. You can check it out [here](https://staging-odin-project.herokuapp.com/404)

P.S. I am not too happy with the responsive design of this page. If you have a better solution, please let me know!

### CODE REVIEW

**Comment by KevinMulhern** [comment]
👍 LGTM, Thanks @arku

**Comment by morrowdavidson** [comment]
> P.S. I am not too happy with the responsive design of this page. If you have a better solution, please let me know!

@arku What do you think about moving the `error-page__image <div>` inside `no_found.erb`? Like so:
```HTML
<div class="error-page">
  <div class="col-lg-10 offset-lg-1 col-sm-12">
      <div class="error-message">
        <h1 class="error-message__title">Looks like you're lost, Odinite!</h1>
        <p class="error-message__sub-title">Take me back to <%= link_to 'theodinproject.com', home_path, class: 'error-message__link'%></p>
      </div>
      <div class="error-page__image"></div>
  </div>
</div>
```
That way you wouldn't have to mess with `background-position` at all as the image would just slide down with the message.

**Comment by KevinMulhern** [comment]
Hey @arku what do you think of @morrowdavidson's suggestion?

**Comment by arku** [comment]
@KevinMulhern I have updated my code to @morrowdavidson's suggestions and cleaned up the styles. Can you guys PTAL?

I have deployed the updated version to staging, You can check it out [here](http://localhost:3000/courses/web-development-101111).

**Comment by morrowdavidson** [comment]
LGTM @arku

**Comment by arku** [comment]
@morrowdavidson Thanks for the review!

**Pull request merged**
