### PR TITLE
Update static_pages.css.scss

### PR DESCRIPTION
**Pull request by raditotev**
Set the size of "div .headline h1" for mobiles.

### CODE REVIEW

**Comment by KevinMulhern** [comment]
Hey @raditotev, thanks for doing this 😄

**Comment by raditotev** [comment]
Hey, my pleasure :) I was surprised it's been left for so long.

**Comment by KevinMulhern** [comment]
Yeah It's been on the back burner 😄

**Comment by TopOneOfTopOne** [comment]
The closing bracket is missing please revise this....

**Comment by raditotev** [comment]
Yeah you are right @TopOneOfTopOne . What do you do in this case @KevinMulhern ?

**Comment by KevinMulhern** [comment]
Oh we missed that, It's no big deal @raditotev I'll add it in by editing the file on github 😄

**Comment by raditotev** [comment]
Thanks @KevinMulhern :+1:  :)

**Pull request merged**
