### PR TITLE
Chore: Add test commands for website instructions

### PR DESCRIPTION
**Pull request by thatblindgeye**
Complete the following REQUIRED checkboxes:

-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [x] The title of this PR follows the `keyword: brief description of change` format, using one of the following keywords:
  - `Feature` - adds new or amends existing user-facing behaviour
  - `Chore` - changes that have no user-facing value, refactors, dependency bumps, etc
  - `Fix` - bug fixes

Complete the following checkbox ONLY IF it is applicable to your PR. You can complete it later if it is not currently applicable:
-   [ ] I have verified all tests and linters pass against my changes, and/or I have included automated tests where applicable

<hr>

**1. Because:**

Closes #XXXXX
The Wiki pages need updating/consolidating, and the commands for running tests before submitting PRs needed to be included in the actual contributing guide rather than the (incorrect/outdated) Wiki contributing guide.

**2. This PR:**

- Adds the list of test commands users should run before submitting PRs to the website repo

**3. Additional Information:**

### CODE REVIEW

**Comment by CouchofTomato** [comment]
This is fine at face value

@KevinMulhern Would we consider creating a bin/ci file or something that could just run all these commands for us rather than expecting someone to run them all individually?

**Comment by KevinMulhern** [comment]
@CouchofTomato I would have no issues with that, we could create one for linting and one for tests. Although I'm not sure it would be worth the effort. It's not often you'll find yourself needing to run both js and ruby linters in the same PR locally from my own experience.

**Review by KevinMulhern — APPROVED** [review]
👍  Looks good to me

**Comment by thatblindgeye** [comment]
Would it be worth adding verbiage as to which tests users should run and when, depending on the contents of their PR? Or is it just simpler/find to list those four commands and have them run all of them?

**Comment by KevinMulhern** [comment]
Yeah I think it's worth just making them aware of those commands @thatblindgeye. CI will always automatically run when they create the PR, catching any failing tests or linters so won't be a huge deal if they forget to run them locally.

**Pull request merged**
