### PR TITLE
Update lesson.scss

### PR DESCRIPTION
**Pull request by Deetss**
fixes percent completed on mobile

### CODE REVIEW

**Comment by KevinMulhern** [comment]
Hey @Deetss, sorry its taken me a few days to have a look at this. We will be shipping the redesigned site next week. This change won't be applied to the redesigned site as these styles have all been deleted and this problem is fixed on the redesigned site. 

I'm going to close this instead of merging it, as it cause a conflict when we merge in with the redesign changes next week.

Thanks for opening this pull request though, and don't let it put you off contributing in the future. If we got a pull request like this a couple of months ago we would have merged it in a heart beat. It's just unfortunate timing for this PR with the redesign about to be deployed. I hope you understand.

If you have any questions about this don't hesitate to reach out.

**Comment by Deetss** [comment]
hey do you know if it will still go towards the hacktoberfest?

**Comment by CouchofTomato** [comment]
@Deetss You can check your hacktoberfest contributions by entering your github username here https://hacktoberfestchecker.herokuapp.com/

**Comment by Deetss** [comment]
@CouchofTomato Thank you, that rocks!

**Pull request closed without merging**
