### PR TITLE
Add threading to rake task

### PR DESCRIPTION
**Pull request by TopOneOfTopOne**
There is a bug for me where the same lessons are being updated even when it has not changed. It is really weird...

Anyway this will significantly reduce the time it takes to update content however there are a few caveats you should be aware of 

1. I tried lowering number of threads but database error is thrown
2. Occasionally errors will be thrown but rerunning rake task usually solves it
3. Output is well.. ugly lol

In my opinion I would be tentative to add this into production but I use it in my development environment.

### CODE REVIEW

**Comment by KevinMulhern** [comment]
Hey @TopOneOfTopOne, thank you for the pull request 😄 

This task is automated on our server and runs every few hours to mostly pull in the new student submissions that have been merged. In reference to the caveats you mentioned the first two concern me, rerunning the task wont really be an option and I would like to know what the database error is? We wouldn't really be concerned with ugly output. Also did you check to make sure all the tests are still passing? you haven't made any changes to the spec file for the task.

**Comment by TopOneOfTopOne** [comment]
The database times out, I think this is caused by reading and writing to the database too many times at once. I read on stackoverflow you can increase pools but I am not too sure about this. 

For the current implementation in the pull request this error is a problem `Faraday::ConnectionFailed: Failed to open TCP connection to api.github.com:443 (getaddrinfo: nodename nor servname provided, or not known)` but actually I don't think this is a problem since I suspect this has something to do with DNS resolution thus it maybe more todo with issues with my own internet.

Yes the tests pass but they don't really evaluate the use of multi threading. I guess I could try to add additional tests but the threads don't share any information so it should be fine. 

If the task is automated then I see no use for this in production then, no need to compromise anything for performance gains that we won't even notice... However I think this would be great for development.

Lastly have you noticed the strange bug? I couldn't figure what was causing it.

**Comment by KevinMulhern** [comment]
No problem, we can use this in development as you mentioned :)
can you create a new file with this version of the task and call it something like `development_curriculum.rake`

**Comment by TopOneOfTopOne** [comment]
Done I have both versions now and I will add the issue for people who are smart than me to solve

**Comment by KevinMulhern** [comment]
Thanks @TopOneOfTopOne I'll get this one and your other PR tested on my local machine and get them merged. Hopefully later today.

**Pull request merged**
