### PR TITLE
add faq question and answer about a course certificate

### PR DESCRIPTION
**Pull request by CouchofTomato**

### CODE REVIEW

**Comment by KevinMulhern** [comment]
Thanks for this @CouchofTomato 

I think this part could be picked up the wrong way. Maybe we should say something along the lines of employers will be much more interested in seeing what you can do and have done via your portfolio instead of a certificate

`No. A certificate for completing The Odin Project won\'t get you a job`

**Comment by codyloyd** [comment]
I like how straightforward it is though....
maybe:
> Employers don't care about certificates, what they care about is whether or not you can __code__, which is displayed in ~a bitchin~ an awesome portfolio of projects....

**Comment by CouchofTomato** [comment]
Ok, have a look now lovers xx

**Comment by KevinMulhern** [comment]
👍 LGTM

**Pull request merged**
