### PR TITLE
Add learners' dashboard view

### LINKED ISSUE #510: Redesign: Dashboard
This task is to implement a dashboard page as shown in the mock up images below. You can use the users show controller action and view for this page.

**Important**
Please ignore the solutions component at the bottom of the mock up. We will create another issue for implementing that feature when we merge in the backend work for it in the next few weeks.

### Working on this task

- [ ] If you want to work on this task, please claim it by commenting below   
- [ ] Branch off the redesign branch                                                                 
- [ ] Check out our [styleguide](https://staging-odin-project.herokuapp.com/styleguide)
- [ ] When you are submitting your pull request for this task please ensure the base branch you want to merge into is the redesign branch  

If you have any questions or need clarification about anything related to this task please contact the maintainers in our [contributing channel on Gitter](https://gitter.im/TheOdinProject/Contributing)

### Redesigned lesson page mock up
dashboard-complete

### PR DESCRIPTION
**Pull request by arun1595**
Fixes #510

### CODE REVIEW

**Comment by codyloyd** [comment]
arun.. looks good at first glance through the code... I haven't pulled it and poked around locally yet, but will try to get to that later today

**Comment by KevinMulhern** [comment]
Everything here is well thought out and designed, all those components 😍 

Can't wait to see this one on staging

LGTM 👍 👍 👍

**Comment by codyloyd** [comment]
looks good to me man.

**Comment by KevinMulhern** [comment]
lets :shipit:

**Pull request merged**
