### PR TITLE
Improve the `seed.rb`

### PR DESCRIPTION
**Pull request by herminiotorres**
- Remove espace and blank line.
- Change hash format ruby 1.8 to ruby 1.9.
  e.g: `:key => 'value'` to `key: 'value'`
- Add some comments as documentation. Use [tomdoc](http://tomdoc.org) format.

### CODE REVIEW

**Comment by KevinMulhern** [comment]
Hey @herminiotorres thanks for the PR, I can't comment much because the diff is to large to view on Github lol, I will have to get a git client and view it on there. Only thing I did notice was the English in the comments was a little bit broken in some parts, but I understand english isn't your first language so don't worry about that. I can help sort those parts out.

**Comment by herminiotorres** [comment]
@KevinMulhern thanks for this some improve with english! :)

**Comment by KevinMulhern** [comment]
No problem :+1: great work though, its looking much more structured after your changes :smile:

**Comment by herminiotorres** [comment]
it compares the title of the course, it is not very cool, better if each course and section has a pattern of number and change it.

**Comment by muzfuz** [comment]
Agreed.  Maybe there is a better way to structure course titles according to some pattern.  However it needs to be clear and simple enough that it is easily readable.

**Comment by herminiotorres** [comment]
I found this too long file, maybe extract to yaml these data and require in seed this yaml, it might be a good idea and could separate the structures course, so it can leave more readable

**Comment by herminiotorres** [comment]
I think this inside point of view could be apply in another pull-request when this approve.

**Comment by muzfuz** [comment]
Ok sounds good.  @KevinMulhern ?

**Comment by KevinMulhern** [comment]
I'll edit the comments today, Ill comment again when it's done. Sounds good about tackling the other stuff when this one is done :smile:

**Comment by herminiotorres** [comment]
@KevinMulhern what do you think is missing? for is completed this pull-request?

**Pull request merged**
