### PR TITLE
Fix: Community & Installation Guides: Make full cards clickable

### PR DESCRIPTION
**Pull request by JoshDevHub**
## Because

For both the installation guide index and the community guide show page, the full size for the card links isn't clickable. Here's a quick gif of what I mean:

guide_links

Or, a link to the relevant pages to try for yourself:
- [installations](https://www.theodinproject.com/guides/installations)
- [community guides](https://www.theodinproject.com/guides/community)

## This PR

- Styles these cards such that their links are clickable along the full height and width of the card.

Another quick gif with my changes:
guide_links_fix

## Issue

Closes #XXXXX

## Pull Request Requirements

-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [x] The title of this PR follows the `keyword: brief description of change` format, using one of the following keywords:
    - `Feature` - adds new or amends existing user-facing behavior
    - `Chore` - changes that have no user-facing value, refactors, dependency bumps, etc
    - `Fix` - bug fixes
-   [x] The `Because` section summarizes the reason for this PR
-   [x] The `This PR` section has a bullet point list describing the changes in this PR
-   [x] I have verified all tests and linters pass after making these changes.
-   [ ] If this PR addresses an open issue, it is linked in the `Issue` section
-   [ ] If applicable, this PR includes new or updated automated tests

### CODE REVIEW

**Comment by JoshDevHub** [comment]
Ah weird -- in the deployment the `p-0` doesn't cascade properly on the wrapper div:
```erb
<div class="p-8 p-0">
  <a> 
    <!-- the link -->
  </a>
</div>
```
Locally, the `p-0` utility takes control for me here, but in the deploy, the `p-8` utility is still applied.

**Comment by JoshDevHub** [comment]
Okay poked around a bit and was reminded that Tailwind doesn't guarantee any type of "cascade" on the same utilities, which I knew but forgot :upside_down_face:

I guess this is why the previous code uses `px` and `py` to override the component's default? I'll try it using that same technique and see how it works.

**Comment by JoshDevHub** [comment]
Okay looks good now on the deploy :rocket:

**Review by KevinMulhern — APPROVED** [review]
Looks great to me, thanks @JoshDevHub 

The specificity issue is weird. px-0 wouldn't work for me locally, until I clobbered the assets. Our assets have only been semi-trustworthy since css bundling was introduced and might have something to do with it.

**Pull request merged**
