### PR TITLE
homepage button

### PR DESCRIPTION
**Pull request by JonathanYiv**
As mentioned in Gitter
To be a placeholder until a final decision is made

### CODE REVIEW

**Comment by KevinMulhern** [comment]
This looks good @JonathanYiv, thanks for opening it. I think we  should try a/b testing this with google analytics. We can do 3 tests at the same time which is pretty cool.

To do that we we will need to add a param to the url. Can you change it the code to this please?

```
<% if param[:start_now] %>
  <%= link_to 'Start Now!', courses_path,  class: 'button button--primary' %>
<% elsif param[:view_full] %>
  <%= link_to 'View full Curriculum', courses_path,  class: 'button button--primary' %>
<% else %>
  <%= sign_in_or_view_curriculum_button %>
<% end %>
```

Then when you use the different params in the url you will see different variations of the button, for example:

`localhost:3000/?start_now=1` will display the "start here" button. 

Oh and can we change the start here button to bring the user straight to web dev 101 instead please?

**Comment by JonathanYiv** [comment]
Will do in a bit! That's pretty cool that we can test different versions. 
Would the additional query parameter be added by the router?

**Comment by JonathanYiv** [comment]
Updated. What's next?

**Comment by KevinMulhern** [comment]
Sorry for the late reply @JonathanYiv, I've been looking into this a bit more and it seems we might have to do this with javascript in order to run different variations of the button with google analytics. How it divides up the traffic hasn't been made very clear in their guides.

If it turns out to be too complex we could try different variations of the button for a week at a time and seeing how each performs in the metrics.

**Comment by KevinMulhern** [comment]
Going to ship this so I can experiment a big more with google analytics

**Comment by JonathanYiv** [comment]
OK! Let me know if there's more I can do with this issue. I'm honestly completely unfamiliar with JS

**Pull request merged**
