### PR TITLE
Add success_stories page

### PR DESCRIPTION
**Pull request by gionaufal**
Add success_stories page based on the layout on issue #403 
The style was made on the existing success_stories.scss

### CODE REVIEW

**Comment by KevinMulhern** [comment]
Hey @gionaufal, this is looking really good 😄 the new `success_stories.html.erb` view doesn't seem to be included though?

**Comment by gionaufal** [comment]
sorry @KevinMulhern! Now it is :smile:

**Comment by KevinMulhern** [comment]
@gionaufal excellent work, I can't wait to see this page in production 😄 

LGTM 👍  💯

**Comment by gionaufal** [comment]
Thank you @KevinMulhern! I'm glad I could help, and will keep an eye to see if I can get another issue to work on :smiley:

**Pull request merged**
