### PR TITLE
mobile navbar

### LINKED ISSUE #455: Redesign: Mobile view Navigation Bar
This task involves creating the mobile media queries (320px width) for the navigation bar. The navbar will stick to the top of the viewport.

Comment your email to get access to the Zeplin file for full design details https://zpl.io/14dBXX
Please refer to the Zeplin file's details for spacing, sizing and typography!!!! 🔍

This is the 📱 mobile view you'll be creating for the nav bar:

screen shot 2017-04-28 at 1 15 52 am

Keep in mind that the nav bar has a background that is blurred, so it would look like this when the page scrolls up. Check Zeplin for all the details for the values.

screen shot 2017-04-28 at 1 49 28 am

The nav bar drop down menu is in another issue #456 

### Working on this task

- [ ] If you want to work on this task, please claim it by commenting below   
- [ ] Branch off the redesign branch                                                                 
- [ ] When you are submitting your pull request for this task please ensure the base branch you want to merge into is the redesign branch

### PR DESCRIPTION
**Pull request by codyloyd**
fixes #455

### CODE REVIEW

**Comment by adachiu** [comment]
Cody, can you lighten the opacity for the shadow so it is more subtle?

**Comment by codyloyd** [comment]
gladly!

**Comment by codyloyd** [comment]
@adachiu hows this?
easy to change the size as well if you like.

**Comment by adachiu** [comment]
Viewing it from my phone. It looks good!

**Comment by KevinMulhern** [comment]
👍 LGTM

**Pull request merged**
