### PR TITLE
Fix: support for ios

### PR DESCRIPTION
**Pull request by DoviMaj**
Fix: Support for *Safari

Replaces all `flexbox-gap` instances with `margin`.

### CODE REVIEW

**Comment by KevinMulhern** [comment]
Thanks @DoviMaj, this looks great on larger screens 💪 

It looks like we'll need a breakpoint for putting some margin between the buttons mobile screens however:

Screenshot 2021-04-14 at 23 47 08

**Comment by DoviMaj** [comment]
Good catch! done

**Comment by DoviMaj** [comment]
Actually, I checked and `:nth-child` doesnt have great support for Opera, Samsung and Chrome for Android. Better use a different solution right?

https://caniuse.com/?search=%3Anth-child

**Comment by KevinMulhern** [comment]
I think it should be fine @DoviMaj, the support for the newer version of :nth-child child isn't great but you're not using any of its features here mate 😄

**Review by KevinMulhern — APPROVED** [review]
Great work @DoviMaj, looks ace on mobile.

**Pull request merged**
