### PR TITLE
Fix: Correct JSON lesson order in course fixtures

### PR DESCRIPTION
**Pull request by JoshDevHub**
## Because

In #4326 I forgot to edit the course fixtures (which determine the order the lesson appears in the course). So this is basically just correcting my oversight in that PR :upside_down_face: 

Double checked that it's fully functional this time by populating the curriculum content locally and checking that things are in order. Lesson learned on that one.

## This PR

- Fixes the ordering of the JSON lesson in the JavaScript course for both paths.

## Issue

Closes #XXXXX

## Pull Request Requirements

-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [x] The title of this PR follows the `keyword: brief description of change` format, using one of the following keywords:
    - `Feature` - adds new or amends existing user-facing behavior
    - `Chore` - changes that have no user-facing value, refactors, dependency bumps, etc
    - `Fix` - bug fixes
-   [x] The `Because` section summarizes the reason for this PR
-   [x] The `This PR` section has a bullet point list describing the changes in this PR
-   [x] I have verified all tests and linters pass after making these changes.
-   [ ] If this PR addresses an open issue, it is linked in the `Issue` section
-   [x] If applicable, this PR includes new or updated automated tests

### CODE REVIEW

**Review by ChargrilledChook — APPROVED** [review]

**Comment by JoshDevHub** [comment]
Oh weird. PRs from a forked origin can't be previewed?

**Comment by KevinMulhern** [comment]
@JoshDevHub yeah its a pain, we've got an issue about it [here](https://github.com/TheOdinProject/theodinproject/issues/3193). I'll kick off a manual review app deploy for this PR mate.

**Comment by JoshDevHub** [comment]
Awesome thank you @KevinMulhern 

In the preview app, the JSON lesson is in the updated placement in the JavaScript course for the Node and Rails paths. But if I try to visit the lesson, it hits me with a 500 error. Do you have any idea why that might be happening? I can navigate to it fine locally.

**Comment by KevinMulhern** [comment]
Looks like its trying to fetch the content using old path on the review app @JoshDevHub  
Screenshot 2024-01-13 at 22 31 24

Rebasing with main should hopefully sort it out.

**Comment by JoshDevHub** [comment]
Yep that did it @KevinMulhern :raised_hands: 

Thanks for the help.

**Pull request merged**
