### PR TITLE
Delete the CSS Grids Lesson

### PR DESCRIPTION
**Pull request by SilasSpet**
This is the corresponding pull request to [curriculum issue #11867](https://github.com/TheOdinProject/curriculum/issues/11867) with the [pull request #11868](https://github.com/TheOdinProject/curriculum/pull/11868) . You can find an explanation to these changes and the reason for them over there.

### CODE REVIEW

**Comment by codyloyd** [comment]
@KevinMulhern can you confirm that this isn't going to make anything explode?  I approve of removing this lesson.

**Comment by arku** [comment]
@codyloyd This is removing the lesson from the seeds file. We will still have to delete the lesson from the database with a rake task or something.

/cc @KevinMulhern

**Comment by zachmmeyer** [comment]
How do you go about removing the lesson from the database? This lesson should be removed if that is the general consensus.

**Comment by KevinMulhern** [comment]
Sorry it's taken me so long to get on this. I'll create a rake task to remove the lesson from the db.

**Pull request merged**
