### PR TITLE
Upgrade/font awesome 5

### PR DESCRIPTION
**Pull request by morrowdavidson**
Maybe this should go in a dev branch for a future update and so we can check the icons are updated everywhere... Removed the gem and used the CDN instead. Then followed [these instructions](https://fontawesome.com/how-to-use/on-the-web/setup/upgrading-from-version-4)

### CODE REVIEW

**Comment by KevinMulhern** [comment]
Thanks @morrowdavidson, this looks good.

I'll deploy to the staging server so we can have a good look over it https://staging-odin-project.herokuapp.com

**Comment by morrowdavidson** [comment]
Oh ok, if it's going here: https://staging-odin-project.herokuapp.com then I'll get rid of the [shim](https://fontawesome.com/how-to-use/on-the-web/setup/upgrading-from-version-4#shims) so we can see if it breaks anywhere.

**Comment by KevinMulhern** [comment]
@morrowdavidson thats on staging

**Comment by morrowdavidson** [comment]
Thanks guys for looking it over. I looked on the staging server and couldn't find any missing icons.

**Pull request merged**
