### PR TITLE
Fix styling on sign in and sign up pages

### PR DESCRIPTION
**Pull request by arcanck**
#555 Fixed h1 and input styles on sign in and sign up pages.

### CODE REVIEW

**Comment by KevinMulhern** [comment]
👍 LGTM
Thanks @arcanck 😄

**Comment by codyloyd** [comment]
the placeholder color seems to light on my monitor.. it's pretty much impossible to read.  Can we make it $grey instead of $pale-grey ?

**Comment by arcanck** [comment]
@codyloyd, yes. The last commit has placeholder with **$light-grey**, as solicited in the issue. Didn't work? Well, if with **$light-grey** it continues with a bad preview, I can rather make the change.

**Comment by arcanck** [comment]
@codyloyd, the color of the placeholder text was changed to **$light-gray** as requested in the issue. Even with the last commit of this pull request, is the view still poor?

**Comment by codyloyd** [comment]
but light-grey is literally `#eee` don't you think that's too light?
I'll do a screenshot

**Comment by arcanck** [comment]
@codyloyd, reviewing here now, in fact, could be changed. You're right!

**Comment by KevinMulhern** [comment]
Hey @arcanck, are you going to include that change in this PR?

**Comment by KevinMulhern** [comment]
Thanks @arcanck 😄 
LGTM 👍 
@codyloyd what do you think?

**Comment by codyloyd** [comment]
I'm happy

**Comment by KevinMulhern** [comment]
Thanks @arcanck 😄

**Pull request merged**
