### PR TITLE
Fix: Incorrect capitalisation on titles and in lesson overview. Closes: #3812

### LINKED ISSUE #3812: Styling issue: title h1 is incorrectly capitalised in lessons, unlike in the course lesson overview.
Complete the following REQUIRED checkboxes:

-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [x] The title of this issue follows the `brief description of request` format, e.g. `Add dark mode to website`

The following checkbox is OPTIONAL:

-   [x] I would like to be assigned this issue to work on it
- I wouldn't mind working on it if you find this issue valid enough to be worked on in the future, but I have not yet worked with this repo and I am not entirely sure how elaborate that process would be.
<hr>

**1. Description of the Feature Request:**

Currently the lesson `h1` has `text-transform: capitalize;` applied through the `capitalize` class. This will lead to titles like  `Async And Await` and `A Very Brief Intro To CS`. This is not a huge problem but generally in titles, words like `and` or `to` are not capitalized. It seems thought has been put into this for the course overview of lessons but it gets discarded with the `text-transform` on the `h1` title for the individual lessons. 

note that `with` actually is capitalized usually. It's not in the JS course lesson overview for `Form Validation with Javascript` but it is in the h1 of the lesson itself because of the `.capitalize` class. 

**2. Acceptance Criteria:**

- [x] Titles of lessons should be capitalized correctly

**3. Additional Information:**

Course overview:
Screenshot 2023-05-21 at 21 27 57
Lesson title:
Screenshot 2023-05-21 at 21 27 33
Proposed lesson title:
Screenshot 2023-05-21 at 21 28 55

### PR DESCRIPTION
**Pull request by ManonLef**
## Because

- The lesson titles got incorrectly capitalised with `text-transform: capitalize` through the `capitalize` class
- Some lesson titles were incorrectly capitalised regardless of class

## This PR

- fix incorrect capitalisation according to the [Chicago Title Capitalisation style rules](https://capitalizemytitle.com/style/Chicago/)
- remove `capitalize` class from titles
## Issue

Closes #3812

## Additional Information

- rspec test fail for community guides only, this is due to the Ruby version (mine is 3.1.2) according to Chook

## Pull Request Requirements

-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [x] The title of this PR follows the `keyword: brief description of change` format, using one of the following keywords:
  - `Feature` - adds new or amends existing user-facing behavior
  - `Chore` - changes that have no user-facing value, refactors, dependency bumps, etc
  - `Fix` - bug fixes
-   [x] The `Because` section summarizes the reason for this PR
-   [x] The `This PR` section has a bullet point list describing the changes in this PR
-   [x] I have verified all tests and linters pass after making these changes.
-   [x] If this PR addresses an open issue, it is linked in the `Issue` section
-   [ ] If applicable, this PR includes new or updated automated tests

### CODE REVIEW

**Comment by CouchofTomato** [comment]
Thanks for this @ManonLef 

I'm not sure if we can put something in place to stop any new lessons in future not being added with incorrect title formatting if we go down this route.

@KevinMulhern What do you think?

**Comment by ManonLef** [comment]
@CouchofTomato I agree that would be an option, I mentioned the titleize script above but probably came across one that didn’t have a style it adhered to and capitalized all instead 😅. I’m not too well versed in the Ruby tools/gems (yet?!) to be honest.

I do still think this PR is an upgrade from the previous state of the titles in the lessons and especially in the overview (where the discrepancies are much more noticeable). 

Perhaps I could look into the gem and see if I can figure out how to apply it so it will be automated in the future. I could open a new issue for that if you consider merging this for now. 
If I get lost in it I’ll give a heads up, for as I mentioned, this is the first time working with this repo, Ruby, gems etc. 

What do you think?

**Comment by ChargrilledChook** [comment]
I don"t think we're adding lessons so often that this is a huge maintenance burden, and we can  catch it in review if needed

**Comment by CouchofTomato** [comment]
@ChargrilledChook The issue is just one of consistency. Not adding lessons too often is exactly where we're likely to miss formatting of the title in future and because we're no longer calling capitalise on it in the view, it will lead to titles not rendering in a consistent way.

I'll discuss with Kevin since he mostly maintains the web app and if he's happy with the change as is then I'll approve it.

**Review by CouchofTomato — APPROVED** [review]

**Pull request merged**
