### PR TITLE
Rename student_id to user_id. Update relevant models, specs, etc.

### PR DESCRIPTION
**Pull request by Tenacious-Qi**
This addresses issue https://github.com/TheOdinProject/theodinproject/issues/1883. Not quite sure on the proper etiquette regarding assignment of the issue. I acknowledge this was already assigned, but I had the night free and I thought it might be okay since this is a "chore" and it had been a week since it was assigned. 

Summary:
I generated the migration to rename the column and then ran the specs and addressed each failure by section, renaming where necessary. I also updated the file `spec/factories/lesson_completion.rb` to be associated with a user instead of a student.

### CODE REVIEW

**Comment by KevinMulhern** [comment]
Hey @Tenacious-Qi, thanks for taking the time to do this. 

We need to create some documentation in the contributing guide for these situations 🙈 But the process would be to ask the person it was originally assigned to if they are still working on it on the issue and giving them a few days to respond.

@BrianWisniewski are you still working on this one? or are you happy for this to be merged?

Sorry guys, this happens every so often and is a failure on our part for not having a properly documented process in place. I'll get something added this week.

**Comment by Tenacious-Qi** [comment]
Thanks @KevinMulhern that sounds good. Will ping the assignee in the future. I'm fine either way, just happy I got more practice.

**Comment by BrianWisniewski** [comment]
@Tenacious-Qi @KevinMulhern  Have at it! I haven't had much free time lately with AP exams approaching.

**Comment by KevinMulhern** [comment]
No worries @BrianWisniewski, thanks for getting back to us so quickly. Best of luck with your exams mate 😄

**Review by KevinMulhern — APPROVED** [review]
👍 LGTM, thanks @Tenacious-Qi

**Pull request merged**
