### PR TITLE
Fix/install details further dropdown styling

### PR DESCRIPTION
**Pull request by IrritatedEllipses**
It was brought to my attention that the dropdowns in the install fest needed additional styling to draw attention to the fact they can, in fact, be dropped down. 

A cursor change and increasing the bottom margin of both should help them stand out even more.

### CODE REVIEW

**Comment by arun1595** [comment]
@IrritatedEllipses Thanks for the PR :slightly_smiling_face: 

Can you post a screenshot showing your changes? And please fix the merge conflict.

**Comment by IrritatedEllipses** [comment]
@arun1595 Unfortunately it's going to be just a little bit until I can post a screenshot (Having issues with a wireless adapter and linux at the moment) but I will get it to you as soon as I can.

The merge conflict has been fixed in the meantime.

**Comment by KevinMulhern** [comment]
Very nice change @IrritatedEllipses 
LGTM 👍

**Comment by KevinMulhern** [comment]
@arun1595 I think we can get away with a screen shot such a small change. But I agree any PR's that have frontend changes should probably have screen shots. What do you think about having a PR checklist that includes stuff like that?

**Pull request merged**
