### PR TITLE
Redesign curriculum details section of home page

### LINKED ISSUE #449: Redesign: Mobile view Courses (Home page)
This task involves creating mobile media queries (320px width) for the `Courses` section on the home page.

Comment your email to get access to the Zeplin file for full design details https://zpl.io/14dBXX
**Please refer to the Zeplin file's details for _spacing, sizing and typography_!!!!** 😄 

This is the 📱  mobile view you'll be creating:

screen shot 2017-04-28 at 12 35 48 am

This is the 💻 laptop view just for reference to see (this will be another issue)

screen shot 2017-04-28 at 12 43 06 am

### Working on this task

- [ ] If you want to work on this task, please claim it by commenting below   
- [ ] Branch off the redesign branch                                                                 
- [ ] When you are submitting your pull request for this task please ensure the base branch you want to merge into is the redesign branch

### LINKED ISSUE #450: Redesign: Courses section on Home page
This task involves updating the `Courses` section on the home page (1440px width).

Comment your email to get access to the Zeplin file for full design details https://zpl.io/14j8Nn
**Please refer to the Zeplin file's design details for _assets, spacing, sizing and typography_!!!!** 👍  

screen shot 2017-04-28 at 12 43 06 am

### Working on this task

- [ ] If you want to work on this task, please claim it by commenting below   
- [ ] Branch off the redesign branch                                                                 
- [ ] When you are submitting your pull request for this task please ensure the base branch you want to merge into is the redesign branch

### PR DESCRIPTION
**Pull request by arun1595**
Fixes #449, Fixes #450

### CODE REVIEW

**Comment by KevinMulhern** [comment]
👍 LGTM

**Comment by codyloyd** [comment]
notes:
- (desktop and mobile) need less padding between bottom tile and bottom of section (keep button vertically centered)
- (mobile) more padding between title and stacks
- (mobile) less padding between 'stacks' and 'tiles' (keeping the text vertically)
- (mobile) tiles should be 270px... the issue is the line break on the HTML+CSS3 tile.
  - on that topic, shouldn't we just do CSS instead of CSS3?
- why not put the 'mobile' card breakpoint at around 570px where the tiles break down to a single column

Code looks fine to me 💃

**Comment by arun1595** [comment]
@codyloyd

> (desktop and mobile) need less padding between bottom tile and bottom of section (keep button vertically centered)

Done.

> (mobile) more padding between title and stacks
> (mobile) less padding between 'stacks' and 'tiles' (keeping the text vertically)

Done.

> (mobile) tiles should be 270px... the issue is the line break on the HTML+CSS3 tile.

The issue is that I've set a max-width of 254px on the tile. Fixed by setting a max-width of 270px on the tile in xs devices.

> on that topic, shouldn't we just do CSS instead of CSS3?

You're right. :+1: 

> why not put the 'mobile' card breakpoint at around 570px where the tiles break down to a single column?

I was thinking about it but wasn't sure. Done.

**Comment by arun1595** [comment]
@codyloyd Addressed your review comments. PTAL.

**Comment by KevinMulhern** [comment]
LGTM 👍

**Comment by codyloyd** [comment]
nice!

**Pull request merged**
