### PR TITLE
Feature: Relocate Node.js installation lesson

### PR DESCRIPTION
**Pull request by Eduardo06sp**
## Because

we are replacing Replit exercises with ones from `javascript-exercises`, so we need to do set up for Node.js earlier in the JavaScripts Basics course.

## This PR

* Moves the Installing Node.js lesson so it is right before the Data Types and Conditionals lesson
  - The Data Types and Conditionals lesson is where we will have new material from `javascript-exercises`

## Issue

Related to https://github.com/TheOdinProject/curriculum/issues/29054

## Additional Information

Since multiple repos are affected simultaneously, it may be ideal to merge all 3 PRs at once:

**Blockers:**
* Need to add the four new exercises to the `javascript-exercises` repo - https://github.com/TheOdinProject/javascript-exercises/pull/509
* Need to update the appropriate lessons within our `curriculum` repo to replace the Replit lessons currently there - https://github.com/TheOdinProject/curriculum/pull/29161

I will link the relevant PRs here in a moment after I create them.

## Pull Request Requirements

-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [x] The title of this PR follows the `keyword: brief description of change` format, using one of the following keywords:
    - `Feature` - adds new or amends existing user-facing behavior
    - `Chore` - changes that have no user-facing value, refactors, dependency bumps, etc
    - `Fix` - bug fixes
-   [x] The `Because` section summarizes the reason for this PR
-   [x] The `This PR` section has a bullet point list describing the changes in this PR
-   [ ] I have verified all tests and linters pass after making these changes.
-   [x] If this PR addresses an open issue, it is linked in the `Issue` section
-   [ ] If applicable, this PR includes new or updated automated tests

### CODE REVIEW

**Comment by Eduardo06sp** [comment]
`yarn lint` and `yarn test` were not working properly for me,
but I am confident that it probably won't make a difference due to the type of change I made

**Comment by MaoShizhong** [comment]
`yarn lint` runs fine for me and `yarn test` no longer exists, and will be corrected when #4856 is completed.

**Review by KevinMulhern — APPROVED** [review]
Thanks @Eduardo06sp, this looks great to me!

I wonder if we should go a step further and move the node installation to the first spot in the JS section. I think it might flow better and avoid learners needing to context switch to an installation lesson when they are just getting started with JS. 

But, I do like the idea of keeping preparation lessons like this one as close as possible to where they are useful like you have here.

Whats your thoughts?

**Comment by Eduardo06sp** [comment]
@KevinMulhern I'm personally a huge fan of context switching in this case.

I love that you start to get into JavaScript for the first time, do **a lot** of reading, then you get an "easy" installation lesson next.

I just imagine a learner engaging in learning JS for the first time with a potentially huge cognitive load doing a ton of reading (which although not liked by many, is necessary). Then they just hit an installations lesson which is a much easier walkthrough that lets their brain rest. Then they continue learning more JavaScript.

This is could force a bit of spaced repetition as well, depending on rate of lesson completion.

I may be overthinking it, but this is why I would favor putting Installing Node.js right before the lesson it's used in as opposed to anywhere before that. Regardless, I absolutely would not mind making a change if you prefer the increased levels of simplicity and organization of doing installation stuff up front instead, before all of the JavaScript lessons.

**Comment by KevinMulhern** [comment]
That sounds like solid reasoning to me! thanks @Eduardo06sp.

**Pull request merged**
