### PR TITLE
Feature: add Tailwind CSS class 'rounded-2xl'

### PR DESCRIPTION
**Pull request by VenkaSri**
## Because

[Adding border radius to course links on the landing page](https://github.com/TheOdinProject/theodinproject/discussions/4142#discussioncomment-7022827)

## This PR

- added tailwind class 'rounded-2xl' to _curriculum.html

## Issue

Related to #4142 

## Pull Request Requirements

-   [X ] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [ X] The title of this PR follows the `keyword: brief description of change` format, using one of the following keywords:
    - `Feature` - adds new or amends existing user-facing behavior
    - `Chore` - changes that have no user-facing value, refactors, dependency bumps, etc
    - `Fix` - bug fixes
-   [X ] The `Because` section summarizes the reason for this PR
-   [X ] The `This PR` section has a bullet point list describing the changes in this PR
-   [X ] I have verified all tests and linters pass after making these changes.
-   [ ] If this PR addresses an open issue, it is linked in the `Issue` section
-   [ ] If applicable, this PR includes new or updated automated tests

### CODE REVIEW

**Comment by ManonLef** [comment]
Thanks so much for doing this @VenkaSri !

While playing around on [another PR here](https://github.com/TheOdinProject/theodinproject/pull/4125) I started looking into our path layout, noticing they utilize rounded-lg on the path sections:
Screenshot 2023-09-18 at 20 59 18

I played around a bit and would love some opinions from you and @KevinMulhern on if that would be a better fit here:

## rounded-lg

Screenshot 2023-09-18 at 21 58 53

## rounded-2xl

Screenshot 2023-09-18 at 21 58 53

I hope I'm not a bother for I think the `rounded-lg` might be closer to what you initially proposed in your issue where I proposed keeping it consistent with the team cards PR. I know this is up for personal preference as well. I personally prefer the `rounded-lg` but would love to hear your input (or others reading this)

**Comment by KevinMulhern** [comment]
`rounded-lg` gets my vote 🗳️

**Comment by VenkaSri** [comment]
For my original [proposal](https://user-images.githubusercontent.com/53845532/268422520-e094b217-1b83-498d-ab83-8e234c647f40.png) I had used `rounded-md` to ensure consistency with the all the other button links within the homepage, which all use the same border radius. I like both `md` and `lg`.


Also, the spacing of the h3 in middle card seems off cause of the neighbouring cards.
Screenshot 2023-09-18 at 10 33 09 PM

Made some minor changes to address that. What do you guys think? @ManonLef @KevinMulhern 
Screenshot 2023-09-18 at 10 36 00 PM

**Comment by KevinMulhern** [comment]
Theres not a lot between md and lg, but I think lg looks slightly better in this case.

I'm not sure about the centered text, can you take a screenshot of all the badges to see what it looks like within the overall section please?

**Comment by VenkaSri** [comment]
Looks better imo, @KevinMulhern 
Screenshot 2023-09-19 at 9 24 32 AM

**Comment by KevinMulhern** [comment]
It looks decent to me, what do you think @ManonLef? 

We'd probably be best reworking these components to have more horizontal space for longer titles, but thats getting way out of scope of what we're trying to do here. Something to do in a follow up maybe.

**Comment by ManonLef** [comment]
Yes I might like it better too, It makes the taller row less top heavy for JavaScript. It would need a lot more space to make it all fit horizontally. Definitely something we could look at in the future.

The changes are not showing on the deployment yet, so I suggest you commit the `rounded-lg` version with the proposed alignment changes @VenkaSri so we can review and approve it then!

**Comment by VenkaSri** [comment]
> Yes I might like it better too, It makes the taller row less top heavy for JavaScript. It would need a lot more space to make it all fit horizontally. Definitely something we could look at in the future.
> 
> The changes are not showing on the deployment yet, so I suggest you commit the `rounded-lg` version with the proposed alignment changes @VenkaSri so we can review and approve it then!

Done :)

**Pull request closed without merging**
