### PR TITLE
Remove title and title_url indices from courses table.

### PR DESCRIPTION
**Pull request by iamjhu**
Addresses Issue #245

### CODE REVIEW

**Comment by KevinMulhern** [comment]
There's a conflict with the schema @iamjhu, It must be due to your other change being merged in 😄 update your master branch and merge it into your branch. It shouldn't be a difficult conflict to resolve 👍

**Comment by iamjhu** [comment]
Sorry about the multiple commits. In the second commit, I accidentally accepted the schema version from the `master` branch instead of from `HEAD`. The third commit fixes this by reverting it back to the schema version originally from `HEAD—the more recent one.

**Comment by arun1595** [comment]
@iamjhu  You can squash those commits into a single one :)

**Comment by KevinMulhern** [comment]
It's not big deal having multiple commits, you will get varied opinions on this but I prefer to keep the history as is. Its you call with squashing them @iamjhu

**Comment by iamjhu** [comment]
@KevinMulhern if you prefer the history as-is, I'm fine with how things are then. :) Thanks @arun1595 for bringing it up though! I didn't know how to squash until you mentioned it and I looked it up. 👍

**Comment by KevinMulhern** [comment]
Thanks @iamjhu 😄

**Pull request merged**
