### PR TITLE
Fix/solutions overflow

### PR DESCRIPTION
**Pull request by DoviMaj**
Solution for https://github.com/TheOdinProject/theodinproject/issues/1666.

Changes: 
* Edit icon instead of the button
* Link to user dashboard on own solution
* Word break for long names on smaller devices
* Flex gap for submission buttons instead of margin-left (because: on mobile the edit icon didn't have proper margin)

Before:
chrome-capture (48)
After: 
chrome-capture (49)

I took a look at the tests and they are passing but the new case of `SubmissionTitle` returning a link or not depending on `isCurrentUsersSubmission`  isn't being tested. not sure if it needs tests though.

### CODE REVIEW

**Review by KevinMulhern — CHANGES_REQUESTED** [review]
This is looking really good @DoviMaj, thanks for taking the time to do this.

I think we should replace the toggle visibility icon with the edit icon however. It looks a bit odd to have an 
icon followed by two buttons and then another icon, replacing the toggle visibility icon aligns the actions and makes them more uniform.

Screenshot 2021-03-02 at 18 32 30

**Comment by DoviMaj** [comment]
Let me change the edit icon width to match the flag..

**Comment by DoviMaj** [comment]
Latest change isnt directly related to the issue at hand. It changes the responsive behavior of the buttons. Because they where taking unnecessary space vertically and didn't align nicely on small to medium viewports.

How it looks now:
Peek 2021-03-03 16-37

**Comment by KevinMulhern** [comment]
Nice work @DoviMaj 💪  this is looking great!

Would you mind removing the VisibleToggle component please? I don't think theres any reason to keep it around anymore since your refactor negates the need for it 😎

**Comment by DoviMaj** [comment]
@KevinMulhern, I'm not sure if u get notifications for open pull requests commits so I'm pinging u here to let u know I have removed the visible toggle component and associated styles as requested, so u can review when u can/want. :smiley: 

Also to ask about the need for tests for this refactor.

**Comment by KevinMulhern** [comment]
Thanks for removing that component @DoviMaj 🎉 

We could add a test for asserting the users title is a link in the submission-title component tests. I think thats the only test this needs. Whats your thoughts?

**Comment by DoviMaj** [comment]
Maybe test also if it's rendering correctly depending on if it is the current user's submission or not

```
  it('displays username if not in dashboard view', () => {
    render(<SubmissionTitle submission={submission} />);
    expect(screen.getByText('TestUser')).toBeInTheDocument();
  });
  it('displays username inside p tag if not in dashboard view and isnt current users submission', () => {
    //not sure why isn't working, returns DIV instead of P
    render(<SubmissionTitle submission={submission} />);
    expect(screen.getByText('TestUser').tagName).toBe('P');
  });
  it('displays a link to user dashboard if not in dashboard view and is current users submission', () => {
    render(<SubmissionTitle isCurrentUsersSubmission submission={submission} />);
    expect(screen.getByText('TestUser')).toHaveAttribute('href', '/dashboard');
  });
```

**Comment by KevinMulhern** [comment]
I don't think we should assert on specific tags like `p`. It makes the test very brittle if we update the type of tag we use for it. 

What about doing something like this @DoviMaj?

```
describe('Submission title', () => {

  describe('when on the dashboard view', () => {
    it('displays the lesson title', () => {
      render(<SubmissionTitle submission={submission} isDashboardView />);
      expect(screen.getByText('Test Title')).toBeInTheDocument();
    });

    it('displays a link to the project', () => {
      render(<SubmissionTitle submission={submission} isDashboardView />);
      expect(screen.getByText('Test Title')).toHaveAttribute('href', 'test_path');
    });
  })

  describe('when not on the dashboard view', () => {
    it('displays submissions username', () => {
      render(<SubmissionTitle submission={submission} />);
      expect(screen.getByText('TestUser')).toBeInTheDocument();
      expect(screen.getByText('TestUser')).not.toHaveAttribute('href', '/dashboard');
    });

    it('displays link to users dashboard when submission belongs to the current user', () => {
      render(<SubmissionTitle submission={submission} isCurrentUsersSubmission />);
      expect(screen.getByText('TestUser')).toHaveAttribute('href', '/dashboard');
    });
  })
});
```

**Comment by DoviMaj** [comment]
Yeah, that makes more sense. submited

**Comment by KevinMulhern** [comment]
Looks like this is good to go 🚀 

Thanks for all your work on this @DoviMaj 😄

**Review by KevinMulhern — APPROVED** [review]

**Pull request merged**
