### PR TITLE
Footer icons

### PR DESCRIPTION
**Pull request by codyloyd**
changed the footer icons to pngs

sorry ada.

### CODE REVIEW

**Comment by codyloyd** [comment]
dangit master

**Comment by KevinMulhern** [comment]
👍 LGTM, should we remove the png images too maybe?

**Comment by adachiu** [comment]
Why not to SVG? 😀

**Comment by codyloyd** [comment]
> Why not to SVG? 😀

dangit

**Comment by adachiu** [comment]
LOL sorry Cody :)

**Comment by KevinMulhern** [comment]
👍 LGTM

**Pull request merged**
