### PR TITLE
Redesign profile

### PR DESCRIPTION
**Pull request by ZmagoD**

### CODE REVIEW

**Comment by eriktrautman** [comment]
Thanks! I like the icons for the social profiles and some of the reorganization you've done.  The orange box-shadows and button text, though, don't fit the overall look and feel so please remove those.

**Comment by ZmagoD** [comment]
ok

**Comment by eriktrautman** [comment]
Looks like we've got failing tests. Please update tests to reflect the new changes.  Thanks!

**Comment by eriktrautman** [comment]
Does the stylesheet load for you?  It does not seem to on my end: 
image

**Comment by ZmagoD** [comment]
ups.. I will check it!

**Pull request closed without merging**
