### PR TITLE
Fix position inconsistency issue with like button

### PR DESCRIPTION
**Pull request by DoviMaj**
fix https://github.com/TheOdinProject/theodinproject/issues/1557

### CODE REVIEW

**Comment by I3uckwheat** [comment]
Please add screenshots and such with your PRs.

**Comment by DoviMaj** [comment]
screenshot of the issue solved that is? @I3uckwheat
because i have attached a screenshot of the issue in the issue linked here

**Comment by I3uckwheat** [comment]
yes, attach an image of it solved.

**Comment by DoviMaj** [comment]
Screenshot_2020-12-08 Project Google Homepage The Odin Project
solved image attached

**Review by KevinMulhern — APPROVED** [review]
Thanks @DoviMaj 💯

**Pull request merged**
