### PR TITLE
Added reveal controller for faq page for #2376

### LINKED ISSUE #2376: Update Javascript handling the FAQ page
#### Description
Some of the legacy Javascript can now be updated so we can eventually remove the depedency on jquery.

As part of this we need to update [this file](https://github.com/TheOdinProject/theodinproject/blob/main/app/javascript/src/js/faq.js) to use a Stimulus Controller.

Suggest reading to help you: https://stimulus.hotwired.dev/ and https://www.betterstimulus.com/

#### Acceptance Criteria:

1. The dependency on JQuery is removed
2. The FAQ page operates as it currently does
3. A stimulus controller is created to handle the interaction

#### Additional Information:

Stimulus controllers are all about finding the correct level of abstraction. The suggested reading for better stimulus covers this.

### PR DESCRIPTION
**Pull request by linkonsat**
Complete the following REQUIRED checkboxes:

-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [x] The title of this PR follows the `keyword: brief description of change` format, using one of the following keywords:
  - `Feature` - adds new or amends existing user-facing behaviour
  - `Chore` - changes that have no user-facing value, refactors, dependency bumps, etc
  - `Fix` - bug fixes

Complete the following checkbox ONLY IF it is applicable to your PR. You can complete it later if it is not currently applicable:
-   [x] I have verified all tests and linters pass against my changes, and/or I have included automated tests where applicable

<hr>

**1. Because:**

This removes the JQuery behavior for the faq page and replaces it with a stimulus controller.

Closes #2376

**2. This PR:**

**3. Additional Information:**

### CODE REVIEW

**Review by CouchofTomato — CHANGES_REQUESTED** [review]
Thanks for this @linkonsat 

I like what you've tried to do in abstracting the controller to be a bit more reusable and not coupled to the DOM elements itself but generally hardcoding values like `hidden` in this way is considered an antipattern in stimulus. You could only reuse this class for toggling the hidden class on an element when really all the class is doing is toggling a css class. You can read a bit about that at https://www.betterstimulus.com/architecture/configurable-controllers.html although the solution is a little dated now and you should instead consider whether we could use the css classes https://stimulus.hotwired.dev/reference/css-classes 

The name of the controller doesn't accurately describe what the controller does. Is it a reveal controller when it's hiding the element? Can we consider another name?

Let me know if you have any questions mate.

**Comment by KevinMulhern** [comment]
Hey @CouchofTomato, the reveal name and having including the hidden class were my suggestions from previous reviews in these PRs:

https://github.com/TheOdinProject/theodinproject/pull/2485
https://github.com/TheOdinProject/theodinproject/pull/2710

I can see what you mean about hardcoding the class. But given this is just for toggling the display of something and a hidden class is pretty much ubiquitous in naming and functionality in every CSS class system I think it's fine to hardcode it here. 

The reveal naming suggestion was ~~stolen~~ inspired by [this package](https://www.npmjs.com/package/stimulus-reveal) 😆.  Do you have any suggestions for another name?

**Comment by CouchofTomato** [comment]
@KevinMulhern I don't have another name if everything else remains the same and since you've reviewed it before I'll leave it in your capable hands mate.

**Review by KevinMulhern — APPROVED** [review]
Thanks for all the time and effort you've put into this @linkonsat 💪

**Review by KevinMulhern — APPROVED** [review]

**Pull request merged**
