### PR TITLE
Fix: Replace React badges with new versions

### PR DESCRIPTION
**Pull request by Asartea**
## Because
- The current ones use the wrong color

## This PR
- Replaces them with new amazing versions by @ManonLef 

## Issue
Closes: #4088 

## Pull Request Requirements

-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [x] The title of this PR follows the `keyword: brief description of change` format, using one of the following keywords:
    - `Feature` - adds new or amends existing user-facing behavior
    - `Chore` - changes that have no user-facing value, refactors, dependency bumps, etc
    - `Fix` - bug fixes
-   [x] The `Because` section summarizes the reason for this PR
-   [x] The `This PR` section has a bullet point list describing the changes in this PR
-   [x] I have verified all tests and linters pass after making these changes.
-   [x] If this PR addresses an open issue, it is linked in the `Issue` section

### CODE REVIEW

**Comment by KevinMulhern** [comment]
Thanks for doing this @Asartea, theres a bit of a bug with the borderless badge. I'm not 100% whats causing the problem is.
Screenshot 2023-09-22 at 21 10 05





But.. this amended version of the full badge seems to work ok for the borderless badge:
badge-react-borderless

**Comment by Asartea** [comment]
Weird; have pushed the new image

**Comment by KevinMulhern** [comment]
Something weird is going on @Asartea, the borderless badge is [missing](https://github.com/TheOdinProject/theodinproject/pull/4163/files#diff-ee256f87ca58b3e6a1f6f887094c250df53497881b21a08a3511cde7f6fc0ee2)

**Comment by KevinMulhern** [comment]
Need any help with this @Asartea?

**Comment by Asartea** [comment]
I'm going to be honest: I thought I pushed something for this and then completely forgot about it. Will try and get a working file up today

**Review by KevinMulhern — APPROVED** [review]
Looks great to me - thanks @Asartea

**Pull request merged**
