### PR TITLE
Feature: Add Community Onboarding Steps

### PR DESCRIPTION
**Pull request by rlmoser99**
Complete the following REQUIRED checkboxes:
-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [x] The title of this PR follows the `keyword: brief description of change` format, using one of the following keywords:
  - `Feature` - adds new or amends existing user-facing behaviour
  - `Chore` - changes that have no user-facing value, refactors, dependency bumps, etc
  - `Fix` - bug fixes

Complete the following checkbox ONLY IF it is applicable to your PR. You can complete it later if it is not currently applicable:
-   [x] I have verified all tests and linters pass against my changes, and/or I have included automated tests where applicable

<hr>

**1. Because:**
* The current community information is buried in Foundations
* These lesson is long and needs to be split into smaller articles
* Every Discord community member needs to be aware of the rules
* Every Discord community member needs to know how to ask a question

Related to https://github.com/TheOdinProject/top-meta/issues/66

**2. This PR:**
* Adds CommunityOnboardingComponent and test
* Adds community controller and route
* Adds community_onboarded and community_onboarding_steps to user model
* Adds update_onboarding_steps to user's controller & route
* Adds tests for user_spec and community#show
* Update user's ability to update onboarding steps
* Translate dashboard_steps markdown to html
* Adds partials for github_link and form for checkbox
* Darkened background of app's checkbox
* Replace ODIN_CHAT_URL with community_path
* Update welcome email templates
* Removes 2 lessons: Asking For Help & Join the Odin Community

**3. Additional Information:**
When this PR is ready to merge (or right after), we will need to make an announcement in Discord because the behavior of the "Community" link is changing drastically.

In addition, after it is merged we will need to change links throughout the curriculum and in Discord's rule channel because this PR changes the id's to more readable format.

### CODE REVIEW

**Comment by CouchofTomato** [comment]
This has probably been discussed but with this change the intention is only those registered for a TOP account will now have access to the discord?

**Comment by rlmoser99** [comment]
@CouchofTomato Good question! Yes, it has been discussed at team meetings and also in this thread with an earlier version of screenshots.
https://discord.com/channels/505093832157691914/945856689360486400/945871399799623691

**Comment by rlmoser99** [comment]
Change Requested: Create a new discord invite link, so that moving forward we can track what invite links people are using.

**Comment by rlmoser99** [comment]
Closing due to the team deciding to not implement this feature. Instead we will be making a community page feature. 
https://github.com/TheOdinProject/top-meta/issues/204

**Pull request closed without merging**
